// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   string    `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64     `json:"id"`
	AccountID int64     `json:"account_id"`
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID        int64     `json:"id"`
	SourceID  int64     `json:"source_id"`
	DestID    int64     `json:"dest_id"`
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
