// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: createAccount :one
INSERT INTO accounts (
  owner, 
  balance
) VALUES (
$1, $2
) RETURNING id, owner, balance, created_at
`

type createAccountParams struct {
	Owner   string
	Balance pgtype.Numeric
}

func (q *Queries) createAccount(ctx context.Context, arg createAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Owner, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
