// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID        int64
	SourceID  int64
	DestID    int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
